config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :setup, :only => [:index]
  resources :livrets do
    resources :assets
  end
  resources :themes
  resources :trips do
    resources :days
    resources :gestions, :only => [:update]
  end
  #resource for stripe payment
  post "/charge" => "gestions#charge", :as => :create_charge


  get  'mappath', to: 'livrets#mappath'
  get  'preview', to: 'livrets#preview'
  root 'static#index'

  end

app/models/theme.rb
class Theme < ApplicationRecord

  validates :name,    presence: true,   uniqueness: true
  validates :descr,   presence: true
  validates :image,   presence: true
  validates :style,   presence: true
  validates :gallery, presence: true

  has_many :day,        :dependent => :destroy

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :only_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to setup_index_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name, :descr, :image, :style, :gallery)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_for(theme) do |f| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>
      <ul>
      <% theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :descr %>
    <%= f.text_area :descr %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :gallery %>
    <%= f.text_area :gallery %>
  </div>

  <div class="field">
    <%= f.label :style %>
    <%= f.text_field :style %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/themes/_theme.html.erb
<!-- Image Section -->
<div class="col-md-6 col-md-4">
  <a href ="<%= theme_path(theme) %>">
  <div class="container-theme">
    <div class="overlay" style="background: url(<%= asset_url(theme.image) %>) center center / cover no-repeat; position: absolute; display: block;"></div>
    <div class="row bottom-space">
        <div class="col-xs-12">
          <span class="txt-on-img txt-uppercase"><%= theme.name %></span>
        </div>
    </div>
  </div>
  </a>
</div>

app/views/themes/_warningoutoftokyo.html.erb
<div class="row text-center tb-padding">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="alert alert-warning"><p><i class="fa fa-2x fa-exclamation"></i></p>
      <p>Cette journée se déroule en dehors de Tokyo.</p>
    </div>
  </div>
</div>

app/views/themes/edit.html.erb
<header class="business-header">
  <p class="bottom-space"></p>
  <h1 class="tagline">ADMIN CONTROL PAGE</h1>
  <h3 class="tagline">EDIT THEME PAGE</h1>
</header>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<header class="intro">
  <div class="slideshow"></div>
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="empty-space"></div>
      </div>
      <div class="row tb-padding tagline text-left">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
          <h1>Composez votre Tokyo</h1>
          <hr>
          <h3>Une expérience sur mesure</h3>
          <p>Personnalisez votre voyage de A à Z et choisissez un thème pour chaque journée. Nous composons
          votre programme de visite personnel sur mesure.</p>
            <%= link_to "Voir les thèmes des visites", '#theme', class: "btn btn-block btn-hop" %>
            <%= link_to "Préparer mon voyage", trips_path, class: "btn btn-block btn-hop" %>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Header -->
<section class="container content-section text-center tb-padding" id="theme">
    <div class="row tb-padding">
      <div class="col-xs-12">
        <h3>Une journée, une ambiance</h3>
        <p class="text-left">Choisissez un thème pour chaque journée de votre séjour et faites-nous confiance pour organiser
          une journée parfaite à votre attention. <br>
          Chaque <%= link_to 'programme de visite', preview_path %> est différent et individuel, composé sur mesure, selon vos préférences.
          Nous prenons soin de créer des expériences originales et interactives qui permettent de s'immerger au coeur d'un Tokyo véritable
          et original.
      </div>
    </div>
    <div class="row" id="themes_select_list">
      <!-- a partial for that -->
      <% @themes.each do |theme| %>
        <div class="col-xs-12 col-sm-6 col-md-4 text-center">
            <%= link_to (theme) do %>
                <div class="thumbnail-container">
                  <%= label_tag("theme_id_#{theme.id}", class: "radio-thumbnail") do
                    radio_button_tag(:theme_id, theme.id) + image_tag(theme.image,
                    class: 'img-responsive img-center thumbnail')
                  end %>
                  <h4 class="text-center txt-on-img"><%= theme.name %></h4>
                </div>
            <% end %>

        </div>
      <% end %>
    </div>
</section>

<section class="container content-section text-center tb-padding">
  <div class="row">
    <div class="col-xs-12 text-left">
      <h4><strong>Connectez-vous et préparer votre voyage maintenant ! C'est gratuit. :)</strong></h3>
      <p> 1. Connectez-vous et créez votre voyage.</p>
      <p> 2. Personnalisez votre voyage et choisissez le thème de vos journées.</p>
      <p> 3. Recevez votre programme de visite sur mesure.</p>
      <%= link_to "Préparer mon voyage !", new_trip_path, class: 'btn btn-hop btn-lg btn-block' %>
    </div>
  </div>
</section>

<section class="intro">
  <div class="commercial-background background-image-03">
      <!-- background image div -->
  </div>
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="empty-space"></div>
      </div>
      <div class="row tb-padding tagline text-left">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
          <h1>Un séjour unique</h1>
          <hr>
          <h3>A partir de 20€ / Jour</h3>
          <p>Ne suivez pas une liste anonyme "Top 10 à Tokyo" comme tout le monde. Offrez-vous une expèrience unique
          et inoubliable.</p>
              <%= link_to "Préparer mon voyage", trips_path, class: "btn btn-block btn-hop" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/themes/new.html.erb
<header class="business-header">
  <p class="bottom-space"></p>
  <h1 class="tagline">ADMIN CONTROL PAGE</h1>
  <h3 class="tagline">NEW THEME PAGE</h1>
</header>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<!-- Intro Header -->
<header class="intro">
  <div class="slideshow" data-images="<%= images_urls_from @theme.gallery %>"></div>
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="empty-space"></div>
      </div>
      <div class="row tb-padding tagline text-left">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
          <h1><%= @theme.name %></h1>
          <hr>
          <p><%= @theme.descr %></p>
              <%= link_to "Préparer mon voyage", trips_path, class: "btn btn-block btn-hop" %>
              <%= link_to "Voir les autres thèmes", themes_path, class: "btn btn-block btn-hop" %>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Header -->
<% if lookup_context.exists?(@theme.name.downcase, ["themes/details/"], true) %>
   <%= render('themes/details/'+@theme.name.downcase) %>
   <% else %>
     <%= render('themes/details/default') %>
<% end %>

<section class="content-section text-center">
  <div class="row">
    <div class="col-xs-12">
      <%= link_to "Voir les autres thèmes", themes_path, class: "btn btn-block btn-hop" %>
    </div>
  </div>
</section>