config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :setup, :only => [:index]
  resources :livrets do
    resources :assets
  end
  resources :themes
  resources :trips do
    resources :days
    resources :gestions, :only => [:update]
  end
  #resource for stripe payment
  post "/charge" => "gestions#charge", :as => :create_charge


  get  'mappath', to: 'livrets#mappath'
  get  'preview', to: 'livrets#preview'
  root 'static#index'

  end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :theme
  has_one :planning, :dependent => :destroy
  has_one :trip, through: :planning

  has_one    :lunch,            :dependent => :destroy
  accepts_nested_attributes_for :lunch
  has_one    :dinner,            :dependent => :destroy
  accepts_nested_attributes_for :dinner

  validates :date, presence: true
  validate :is_in_more_than_14_days?

  after_save :update_day_price

  def update_day_price
    #price of the day :
    new_price = 20
    self.update_column(:price, new_price)
    self.trip.setup_trip_price #update his trip price
  end

  def is_in_more_than_14_days?
    if !date.nil?
      if date < Date.today + 14.days
        errors.add(:date, 'de votre journée ne peut être avant 15 jours.')
        return false
      end
    end
    return true
  end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip,               only: [:show, :new, :edit, :create, :update, :destroy]
  before_action :set_day,                only: [:show, :edit, :update, :destroy]
  before_action :trip_must_be_editable,  only: [:new, :edit, :create, :update, :destroy]
  before_action :format_theme_collection, only: [:new, :edit, :create, :update]

  # GET /days/1
  # GET /days/1.json
  def show
    @images = @day.theme.gallery.split(' ')
    @images.map! do |img|
      ActionController::Base.helpers.asset_url(img)
    end
    @theme = @day.theme
  end

  # GET /days/new
  def new
    @day  = @trip.days.build
    @day.build_lunch
    @day.build_dinner
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = @trip.days.build(day_params)
    respond_to do |format|
      if @day.save
        format.html { redirect_to [@trip, @day], notice: 'Une journée a été ajoutée à votre séjour.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html {
          flash.now[:alert] = "Une erreur s'est produite. Votre journée n'a pas été enregistrée"
          render :new
        }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        @day.save
        format.html { redirect_to @trip, notice: 'Changements enregistrés.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html {
          flash.now[:alert] = "Les changements n'ont pas pu être enregistrés."
          render :edit
        }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to trip_url(@trip), notice: 'Cette journée a bien été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = @trip.days.find(params[:id])
    end

    def set_trip
      if current_user.admin
        @trip = Trip.find(params[:trip_id])
      else
        @trip = current_user.trips.find(params[:trip_id])
      end
    end

    def trip_must_be_editable
      unless @trip.gestion.status == 'new'
        unless current_user.admin
          redirect_to trips_url
          flash[:alert] = "Vous ne pouvez pas modifier ce voyage."
        end
      end
    end

    def format_theme_collection
      @themes = Theme.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date, :comment, :theme_id, :guide,
                                lunch_attributes:  [:id, :todo, :style],
                                dinner_attributes: [:id, :todo, :style],
                                )
    end
end

app/helpers/days_helper.rb
module DaysHelper
  
end

app/views/days/_day.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 text-center height-fixed">
  <%= image_tag day.theme.image, class: "img-circle img-responsive img-center" %>
  <h3><%= day.theme.name %></h3>
  <h4><%= day.date %></h4>
  <div class="row ">
    <div class="col-xs-12">
    <% if day.lunch.todo %>
      <span class="label label-success"><i class="fa fa-check"></i>Déjeuner prévu !</span>
    <% end %>
    <% if day.dinner.todo %>
      <span class="label label-success"><i class="fa fa-check"></i>Dinner prévu !</span>
    <% end %>
    <% if day.guide %>
      <span class="label label-success"><i class="fa fa-check"></i>Avec un guide privé !</span>
    <% end %>
    <span class="label label-success"><i class="fa fa-check"></i>Mon guide-livret personnel inclus !</span>
    </div>
  </div><br>
    <%= link_to 'Details', trip_day_path(@trip, day) %>
    <% if @trip.gestion.status == 'new' %>
      | <%= link_to "Modifier", edit_trip_day_path(@trip, day) %>
      | <%= link_to "Supprimer", trip_day_path(@trip, day), method: :delete, data: {confirm: "Supprimer cette journée ?"} %>
    <% end %>
</div>

app/views/days/_form.html.erb
<header class="business-header">
  <div class="slideshow"></div>
</header>

<%= form_for [trip, day] do |f| %>
<section class="container content-section tb-padding">
  <div class="row text-center">
    <div class="col-md-8 col-md-offset-2">

      <div class="box"><div class="icon"><div class="image"><i class="fa fa-calendar"></i></div></div></div>
      <h3 class="bottom-space">Date de votre journée</h3>
      <div class="form-group">
        <%= f.date_field :date, class: 'input-lg' %><br>
        <% if day.errors.full_messages_for(:date).any? %>
        <div class="alert alert-warning">
          <% day.errors.full_messages_for(:date).each do |error| %>
            <%= error %>
          <% end %>
        </div>
        <% end %>
        <div class="label label-info"><i class="fa fa-info-circle"></i> Veuillez réserver votre séjour 15 jours à l'avance minimum.</div>
      </div>
    </div>
  </div>
  <!-- uncomment to add Private Guide feature
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <ul class="list-group">
        <li class="list-group-item">
          <strong>Je souhaite un guide privé pour m'accompagner toute la journée.</strong> <i>(+ 195€)</i>
          <div class="material-switch pull-right">
            <%= f.check_box :guide, id: "get-a-guide" %>
            <label for="get-a-guide" class="label-success"></label>
          </div>
        </li>
      </ul>
    </div>
  </div>
-->
    <div class="row text-center">
      <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-success"><i class="fa fa-check"></i>
          L'élaboration de votre parcours personnel et de votre guide-livret est inclue pour votre séjour !
        </div>
      </div>
    </div>

    <div class="row text-center tb-padding">
      <div class="col-md-8 col-md-offset-2">
        <div class="box"><div class="icon"><div class="image"><i class="fa fa-cutlery"></i></div></div></div>
        <h3 class="text-center bottom-space">Vos repas</h3>
      </div>
    </div>

    <div class="row bottom-space">
      <div class="col-md-6">
        <%= f.fields_for :lunch do |ff| %>
          <ul class="list-group">
            <li class="list-group-item">
              <strong>Oui, réservez mon déjeuner !</strong>
              <div class="material-switch pull-right">
                <%= ff.check_box :todo, id: "lunchbox" %>
                <label for="lunchbox" class="label-success"></label>
              </div>
            </li>
          </ul>
          <div class="row">
            <div class="col-xs-10 col-xs-offset-2">
              <ul class="list-group">
                <li class="list-group-item">
                  Cuisine simple / déjeuner sur le pouce
                  <div class="material-switch pull-right">
                    <%= ff.radio_button :style, 1, id: 'fast-lunch' %>
                    <label for="fast-lunch" class="label-success"></label>
                  </div>
                </li>
                <li class="list-group-item">
                  Cuisine locale / restaurant familial
                  <div class="material-switch pull-right">
                    <%= ff.radio_button :style, 2, id: 'local-lunch', checked: :true %>
                    <label for="local-lunch" class="label-success"></label>
                  </div>
                </li>
                <li class="list-group-item">
                  Cuisine élaborée / expérience gastronomique
                  <div class="material-switch pull-right">
                    <%= ff.radio_button :style, 3, id: 'gastro-lunch' %>
                    <label for="gastro-lunch" class="label-success"></label>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
        <%= f.fields_for :dinner do |ff| %>
          <ul class="list-group">
            <li class="list-group-item">
              <strong>Oui, réservez mon Diner !</strong>
              <div class="material-switch pull-right">
                <%= ff.check_box :todo, id: "dinnerbox" %>
                <label for="dinnerbox" class="label-success"></label>
              </div>
            </li>
          </ul>
          <div class="row">
            <div class="col-xs-10 col-xs-offset-2">
              <ul class="list-group">
                <li class="list-group-item">
                  Diner simple / petit restaurant local
                  <div class="material-switch pull-right">
                    <%= ff.radio_button :style, 1, id: 'fast-dinner' %>
                    <label for="fast-dinner" class="label-success"></label>
                  </div>
                </li>
                <li class="list-group-item">
                  Cuisine de qualité / restaurant de quartier
                  <div class="material-switch pull-right">
                    <%= ff.radio_button :style, 2, id: 'local-dinner', checked: :true %>
                    <label for="local-dinner" class="label-success"></label>
                  </div>
                </li>
                <li class="list-group-item">
                  Cuisine gastronomique / restaurant haut de gamme
                  <div class="material-switch pull-right">
                    <%= ff.radio_button :style, 3, id: 'gastro-dinner' %>
                    <label for="gastro-dinner" class="label-success"></label>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-md-8 col-md-offset-2">
        <div class="box"><div class="icon"><div class="image"><i class="fa fa-star"></i></div></div></div>
        <h2>Choisissez une ambiance pour votre journée</h2>
      </div>
    </div>

    <div class="row bottom-space">
      <% if day.errors.full_messages_for(:theme).any? %>
      <div class="alert alert-warning">
        <% day.errors.full_messages_for(:theme).each do |error| %>
          <%= error %>
        <% end %>
      </div>
      <% end %>
    </div>

    <div class="row">
      <% @themes.each do |theme| %>
        <div class="col-xs-6 col-sm-4 col-md-3 text-center">
          <div class="thumbnail-container">
            <%= f.label("theme_id_#{theme.id}", class: "radio-thumbnail") do
              f.radio_button(:theme_id, theme.id) + image_tag(theme.image,
              class: 'img-responsive img-center thumbnail')
            end %>
            <h4 class="tagline text-center"><%= theme.name %></h4>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row tb-padding">
      <div class="col-md-8 col-md-offset-2">
        <%= f.text_area :comment, class: "form-control", rows: 5,
              placeholder: "Une demande spéciale pour cette journée ? Dites nous tout ce qui vous semble nécessaire !" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= f.submit 'Enregistrer', class: 'btn btn-block btn-success btn-lg' %>
        <% end %>
      </div>
    </div>

  </div>
</section>

app/views/days/edit.html.erb
<%= render 'form', trip: @trip, day: @day %>

app/views/days/new.html.erb
<%= render 'form', trip: @trip, day: @day %>

app/views/days/show.html.erb
<header class="intro">
  <div class="slideshow" data-images="<%= @images %>"></div>
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="empty-space"></div>
      </div>
      <div class="row tb-padding tagline text-left">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
          <h1><%= @day.theme.name.capitalize %></h1>
          <hr>
          <h3><%= l(@day.date, format: '%A %d %B %Y') %></h3>
          <p><%= @day.theme.descr %></p>
          <%= link_to "Modifier ma journée", edit_trip_day_path(@trip, @day), class: "btn btn-block btn-hop" %>
          <%= link_to "Organisation du séjour", @day.trip, class: "btn btn-block btn-hop" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
          <div class="alert alert-success"><i class="fa fa-check"></i>
            Votre recevrez votre programme de visite sur mesure pour cette journée.
          </div>
          <% if @day.lunch.todo %>
          <div class="alert alert-success"><i class="fa fa-check"></i>
            Nous organisons votre déjeuner pour cette journée !
          </div>
          <% end %>
          <% if @day.dinner.todo %>
          <div class="alert alert-success"><i class="fa fa-check"></i>
            Un programme de visite personnel est prévu pour cette journée.
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

<% if lookup_context.exists?(@day.theme.name.downcase, ["themes/details/"], true) %>
   <%= render('themes/details/'+@day.theme.name.downcase) %>
   <% else %>
     <%= render('themes/details/default') %>
<% end %>

<section id="day-row" class="container content-section text-center">
  <div class="row tb-padding">
    <div class="col-md-10 col-md-offset-1">
      <div class="box"><div class="icon"><div class="image"><i class="fa fa-cutlery"></i></div></div></div>
      <h2>Mon déjeuner</h2>
    </div>
  </div>
  <div class="row">
    <% if @day.lunch.todo %>
      <div class='col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 alert alert-success'>
        <span><i class="fa fa-check"></i></span>
        Nous organisons votre déjeuner !
      </div>
      <div class='col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 alert alert-success'>
        <% if @day.lunch.style == 1 %>
          <span><i class="fa fa-check"></i></span>
          Vous avez choisi un déjeuner <strong>sur le pouce</strong> : un repas simple et
          rapide sur le parcours de vos visites.
        <% elsif @day.lunch.style == 2 %>
          <span><i class="fa fa-check"></i></span>
          Vous avez choisi un déjeuner <strong>local</strong> : un déjeuner japonais typique dans un restaurant de quartier.
        <% elsif @day.lunch.style ==3 %>
          <span><i class="fa fa-check"></i></span>
          Vous avez choisi un déjeuner <strong>gastronomique</strong> : un déjeuner dont vous vous souviendrez dans un restaurant haut de gamme.
        <% end %>
      </div>
      <% else %>
      <div class='col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 alert alert-warning'>
        <span><i class="fa fa-times"></i></span>
        Nous n'organisons pas votre déjeuner.
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <% if @trip.gestion.status == 'new' %>
        <%= link_to "Modifier ma journée", edit_trip_day_path(@trip, @day), class: "btn btn-block btn-success" %>
      <% end %>
      <%= link_to "Planning du séjour",  trip_path(@trip), class: "btn btn-block btn-hop" %>
    </div>
  </div>
  <div class="row tb-padding">
    <div class="col-md-10 col-md-offset-1">
      <div class="box"><div class="icon"><div class="image"><i class="fa fa-cutlery"></i></div></div></div>
      <h2>Mon dîner</h2>
    </div>
  </div>
  <div class="row">
    <% if @day.dinner.todo %>
      <div class='col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 alert alert-success'>
        <span><i class="fa fa-check"></i></span>
        Nous organisons votre dîner !
      </div>
      <div class='col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 alert alert-success'>
        <% if @day.dinner.style == 1 %>
          <span><i class="fa fa-check"></i></span>
          Vous avez choisi un dîner <strong>local</strong> : un dîner dans un restaurant traditionnel familial.
        <% elsif @day.dinner.style == 2 %>
          <span><i class="fa fa-check"></i></span>
          Vous avez choisi un dîner <strong>élaboré</strong> : une cuisine de qualité pour un dîner japonais exceptionnel.
        <% elsif @day.dinner.style ==3 %>
          <span><i class="fa fa-check"></i></span>
          Vous avez choisi un dîner <strong>gastronomique</strong> : Un dîner dans l'un des meilleurs restaurants de la capitale.
        <% end %>
      </div>
      <% else %>
      <div class='col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 alert alert-warning'>
        <span><i class="fa fa-times"></i></span>
        Nous n'organisons pas votre dîner.
      </div>
    <% end %>
  </div>
  <div class="row bottom-space">
    <div class="col-sm-6 col-sm-offset-3">
      <% if @trip.gestion.status == 'new' %>
        <%= link_to "Modifier ma journée", edit_trip_day_path(@trip, @day), class: "btn btn-block btn-success" %>
      <% end %>
      <%= link_to "Planning du séjour",  trip_path(@trip), class: "btn btn-block btn-hop" %>
    </div>
</section>
<% if @day.comment.present? %>
<hr>
<section id="day-row" class="container content-section text-left">
  <div class="row tb-padding">
    <div class="col-xs-12">
      <h4>Commentaire : </h4>
      <p><%= @day.comment %></p>
    </div>
  </div>
</section>
<% end %>