config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :setup, :only => [:index]
  resources :livrets do
    resources :assets
  end
  resources :themes
  resources :trips do
    resources :days
    resources :gestions, :only => [:update]
  end
  #resource for stripe payment
  post "/charge" => "gestions#charge", :as => :create_charge


  get  'mappath', to: 'livrets#mappath'
  get  'preview', to: 'livrets#preview'
  root 'static#index'

  end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :livret

  has_attached_file :map
                     #styles: { medium: "300x300" },
                     #default_url: "/images/:style/missing.png"
  validates_attachment :map, presence: true,
                     content_type: { content_type: "image/jpeg" }
end

app/models/budget.rb
class Budget < ApplicationRecord
  validates :value, presence: true
  belongs_to :trip, required: false
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :theme
  has_one :planning, :dependent => :destroy
  has_one :trip, through: :planning

  has_one    :lunch,            :dependent => :destroy
  accepts_nested_attributes_for :lunch
  has_one    :dinner,            :dependent => :destroy
  accepts_nested_attributes_for :dinner

  validates :date, presence: true
  validate :is_in_more_than_14_days?

  after_save :update_day_price

  def update_day_price
    #price of the day :
    new_price = 20
    self.update_column(:price, new_price)
    self.trip.setup_trip_price #update his trip price
  end

  def is_in_more_than_14_days?
    if !date.nil?
      if date < Date.today + 14.days
        errors.add(:date, 'de votre journée ne peut être avant 15 jours.')
        return false
      end
    end
    return true
  end

end

app/models/dinner.rb
class Dinner < ApplicationRecord
  belongs_to :day, required: false
  #TODO validate style if todo true, voir avec scope
end

app/models/gestion.rb
class Gestion < ApplicationRecord
  belongs_to :trip
  validates :status, presence: true


  def process_stripe_charge(amount, email, token)
    customer = Stripe::Customer.create(
      :email => email,
      :source  => token
    )
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => amount,
      :description => 'Séjour Tokyhop.fun',
      :currency    => 'eur'
    )
    self.update_attributes(:status => :payed,
                           :token => charge.id,
                           :payment_date => Time.now,
                           :amount_payed => amount)
  end

  #Condition to see if an User can make a booking demand for his trip
  def is_bookable?
    if self.trip.days.length > 0 && self.status == "new"
      return true
    else
      return false
    end
  end

  def book_trip
    self.status = 'approved'
  end

  #can only be call by Admin, can update From/To any status
  def update_status(new_status)
    if ['new', 'approved', 'payed', 'final', 'done'].include? new_status
      self.status = new_status
    else
      false
    end
  end

end

app/models/livret.rb
class Livret < ApplicationRecord
  belongs_to :trip

  has_attached_file :htmlbook
  validates_attachment :htmlbook, presence: true,
  content_type: { content_type: "text/html" },
  size: { in: 0..250.kilobytes }

  has_many :assets, :dependent => :destroy,  :inverse_of => :livret
  accepts_nested_attributes_for :assets

end

app/models/lunch.rb
class Lunch < ApplicationRecord
  belongs_to :day, required: false
end

app/models/planning.rb
class Planning < ApplicationRecord
  belongs_to :day, dependent: :destroy
  belongs_to :trip
end

app/models/rythme.rb
class Rythme < ApplicationRecord
  validates :value,     presence: true

  belongs_to :trip, required: false
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :trip, required: false
end

app/models/theme.rb
class Theme < ApplicationRecord

  validates :name,    presence: true,   uniqueness: true
  validates :descr,   presence: true
  validates :image,   presence: true
  validates :style,   presence: true
  validates :gallery, presence: true

  has_many :day,        :dependent => :destroy

end

app/models/trip.rb
class Trip < ApplicationRecord

  validates :name,          presence: true,
                            length: { maximum: 30 }
  validates :pickup_place,  presence: true, length: { maximum: 40 }
  validates :adults,        presence: true
  belongs_to :user

  after_save :setup_trip_price

  has_one    :budget,           :dependent => :destroy
  accepts_nested_attributes_for :budget

  has_one    :rythme,           :dependent => :destroy
  accepts_nested_attributes_for :rythme

  has_one    :style,            :dependent => :destroy
  accepts_nested_attributes_for :style

  has_one    :gestion,          :dependent=>  :destroy
  has_one    :livret,           :dependent=>  :destroy

  has_many   :plannings,                      :dependent => :destroy
  has_many   :days,      through: :plannings

  def setup_trip_price
    #to change price depending of number of people, no change until 4 people
    people_weight = (self.adults + self.kids/2) - 4
    people_weight = 1 if people_weight < 1
    new_price = 9 + (people_weight + 5)
    self.days.each do |day|
      new_price = new_price + day.price
    end
    self.update_column(:price, new_price)
  end

  def can_be_deleted?
    if ['new', 'pending', 'approved'].include? self.gestion.status
        return true
    else
      return false
    end
  end

  def can_be_edited?
    if self.gestion.status == 'new'
      return true
    else
      return false
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  #after_create :send_greeting_email

  has_one :account, :dependent => :destroy
  accepts_nested_attributes_for :account

  has_many :trips, :dependent => :destroy

  validates :email, presence: true
  validates :email, confirmation: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_fbomniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
   end
  end

  def self.from_igomniauth(auth)
    #instagram omniauth - Feature not implemented atm
  end

  def send_greeting_email
    # Sends email to user when user is created.
      MainMailer.greeting_email(self).deliver
  end

end

app/controllers/setup_controller.rb
class SetupController < ApplicationController
  before_action :only_admin
  #This controller is for admin page control
  def index
    @themes = Theme.all
    @users_registered = User.count
    @all_trips = Trip.all
    @trips_total = @all_trips.count
    @last_trips = Trip.last(5)

    @pending_trips = []
    Trip.all.each do |trip|  #TODO has to be done with an activerecord query, thats shit
      if trip.gestion.status == 'approved'
        @pending_trips << trip
      end
    end

    @payed_trips = []
    Trip.all.each do |trip|  #TODO has to be done with an activerecord query, thats shit
      if trip.gestion.status == 'payed'
        @payed_trips << trip
      end
    end

    @final_trips = []
    Trip.all.each do |trip|  #TODO has to be done with an activerecord query, thats shit
      if trip.gestion.status == 'final'
        @final_trips << trip
      end
    end

  end

end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/days_helper.rb
module DaysHelper
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="alert alert-danger">
      <span>#{sentence}</span>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/setup_helper.rb
module SetupHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/setup/_final_trip.html.erb
<li>
  <strong>TripID:<%= final_trip.id %></strong>  | <%= final_trip.user.email %> |
  <%= link_to 'show trip', trip_path(final_trip), class: 'btn btn-warning btn-xs' %>
</li>

app/views/setup/_payed_trip.html.erb
<li>
  <strong>TripID:<%= payed_trip.id %></strong> | <%= payed_trip.name %> | <%= payed_trip.user.email %> |
  <%= payed_trip.adults %>adults & <%= payed_trip.kids %> kids<br>
  <%= payed_trip.price %>€
  <% if payed_trip.livret %>
    <%= link_to "Edit Livret", edit_livret_path(payed_trip.livret), class: 'btn btn-xs btn-info' %>
  <% else %>
    <%= link_to "Add Livret", new_livret_path(trip_id: payed_trip.id), class: 'btn btn-xs btn-info' %>
  <% end %>
  <%= link_to 'Show trip', payed_trip, class: 'btn btn-warning btn-xs' %>
</li>

app/views/setup/_pending_trip.html.erb
<li>
  <strong>TripID:<%= pending_trip.id %></strong> |
  <%= pending_trip.name %> | <%= pending_trip.user.email %> |
  <%= pending_trip.adults %> adults & <%= pending_trip.kids %> kids |
  <%= link_to 'details', trip_path(pending_trip), class: 'btn btn-warning btn-xs' %>
  <%= link_to "Approve this Trip", trip_gestion_path(pending_trip, pending_trip.gestion,
              :status => :approved), :data => {:confirm => 'Approve this trip ?'}, :method => :put,
              class: 'btn btn-success btn-xs' %>
</li>

app/views/setup/index.html.erb
<!-- Header -->
<header class="business-header">
  <div class="slideshow"></div>
  <div class="row">
    <div class="col-xs-12">
      <h1 class="tagline">ADMIN CONTROL CENTER</h1>
    </div>
  </div>
</header>
<!-- Header -->
<section class="container content-section">
    <div class="row">
      <div class="col-xs-12">
        <p><%= @users_registered %> users enregitrés</p>
        <p><%= @trips_total %> trips saved</p>
        <ul>
          <p>5 Last trips saved :</p>
          <% @last_trips.each do |trip| %>
            <li><%= trip.id %> | <%= trip.user.email %> | <%= trip.name %> >>> <%= link_to 'Show', trip %></li>
          <% end %>
        </ul>
      </div>
    </div>
</section>
<hr>
<section class="container content-section">
  <div class="row">
    <div class="col-xs-12">
      <h3>Approved Trip</h3>
      <p>Below are trip with status "approved" : waiting for payment</p>
      <ol>
        <%= render partial: 'pending_trip', collection: @pending_trips %>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <h3>Payed Trip</h3>
      <p>Below are trip with status "payed", Do livret and confirm it</p>
      <ol>
        <%= render partial: 'payed_trip', collection: @payed_trips %>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <h2>Final Trip</h2>
      <p>Final Trip, guy comming</p>
      <ol>
        <%= render partial: 'final_trip', collection: @final_trips %>
      </ol>
    </div>
  </div>
</section>
<hr>
<section class="container content-section">
  <div class="row">
    <div class="col-xs-12">
      <h4>Themes management</h4>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Descr</th>
            <th>Image</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @themes.each do |theme| %>
            <tr>
              <td><%= theme.name %></td>
              <td><%= theme.descr %></td>
              <td><%= theme.image %></td>
              <td><%= link_to 'Show', theme, class: 'btn btn-default btn-xs' %></td>
              <td><%= link_to 'Edit', edit_theme_path(theme), class: 'btn btn-warning btn-xs' %></td>
              <td><%= link_to 'Destroy', theme, class: 'btn btn-danger btn-xs',
               method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Theme', new_theme_path, class: 'btn btn-success' %>
    </div>
  </div>
</section>
<hr>
<section class="container content-section">
  <div class="row">
    <div class="col-xs-12">
      <h4>Trips management</h4>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Status</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @all_trips.each do |trip| %>
            <tr>
              <td><%= trip.name %></td>
              <td><%= trip.user.email %></td>
              <td><%= trip.gestion.status %></td>
              <td><%= link_to 'Show', trip, class: 'btn btn-default btn-xs' %></td>
              <td><%= link_to 'Edit', edit_trip_path(trip), class: 'btn btn-warning btn-xs' %></td>
              <td><%= link_to 'Destroy', trip, class: 'btn btn-danger btn-xs',
               method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>