config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :setup, :only => [:index]
  resources :livrets do
    resources :assets
  end
  resources :themes
  resources :trips do
    resources :days
    resources :gestions, :only => [:update]
  end
  #resource for stripe payment
  post "/charge" => "gestions#charge", :as => :create_charge


  get  'mappath', to: 'livrets#mappath'
  get  'preview', to: 'livrets#preview'
  root 'static#index'

  end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :livret

  has_attached_file :map
                     #styles: { medium: "300x300" },
                     #default_url: "/images/:style/missing.png"
  validates_attachment :map, presence: true,
                     content_type: { content_type: "image/jpeg" }
end

app/models/budget.rb
class Budget < ApplicationRecord
  validates :value, presence: true
  belongs_to :trip, required: false
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :theme
  has_one :planning, :dependent => :destroy
  has_one :trip, through: :planning

  has_one    :lunch,            :dependent => :destroy
  accepts_nested_attributes_for :lunch
  has_one    :dinner,            :dependent => :destroy
  accepts_nested_attributes_for :dinner

  validates :date, presence: true
  validate :is_in_more_than_14_days?

  after_save :update_day_price

  def update_day_price
    #price of the day :
    new_price = 20
    self.update_column(:price, new_price)
    self.trip.setup_trip_price #update his trip price
  end

  def is_in_more_than_14_days?
    if !date.nil?
      if date < Date.today + 14.days
        errors.add(:date, 'de votre journée ne peut être avant 15 jours.')
        return false
      end
    end
    return true
  end

end

app/models/dinner.rb
class Dinner < ApplicationRecord
  belongs_to :day, required: false
  #TODO validate style if todo true, voir avec scope
end

app/models/gestion.rb
class Gestion < ApplicationRecord
  belongs_to :trip
  validates :status, presence: true


  def process_stripe_charge(amount, email, token)
    customer = Stripe::Customer.create(
      :email => email,
      :source  => token
    )
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => amount,
      :description => 'Séjour Tokyhop.fun',
      :currency    => 'eur'
    )
    self.update_attributes(:status => :payed,
                           :token => charge.id,
                           :payment_date => Time.now,
                           :amount_payed => amount)
  end

  #Condition to see if an User can make a booking demand for his trip
  def is_bookable?
    if self.trip.days.length > 0 && self.status == "new"
      return true
    else
      return false
    end
  end

  def book_trip
    self.status = 'approved'
  end

  #can only be call by Admin, can update From/To any status
  def update_status(new_status)
    if ['new', 'approved', 'payed', 'final', 'done'].include? new_status
      self.status = new_status
    else
      false
    end
  end

end

app/models/livret.rb
class Livret < ApplicationRecord
  belongs_to :trip

  has_attached_file :htmlbook
  validates_attachment :htmlbook, presence: true,
  content_type: { content_type: "text/html" },
  size: { in: 0..250.kilobytes }

  has_many :assets, :dependent => :destroy,  :inverse_of => :livret
  accepts_nested_attributes_for :assets

end

app/models/lunch.rb
class Lunch < ApplicationRecord
  belongs_to :day, required: false
end

app/models/planning.rb
class Planning < ApplicationRecord
  belongs_to :day, dependent: :destroy
  belongs_to :trip
end

app/models/rythme.rb
class Rythme < ApplicationRecord
  validates :value,     presence: true

  belongs_to :trip, required: false
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :trip, required: false
end

app/models/theme.rb
class Theme < ApplicationRecord

  validates :name,    presence: true,   uniqueness: true
  validates :descr,   presence: true
  validates :image,   presence: true
  validates :style,   presence: true
  validates :gallery, presence: true

  has_many :day,        :dependent => :destroy

end

app/models/trip.rb
class Trip < ApplicationRecord

  validates :name,          presence: true,
                            length: { maximum: 30 }
  validates :pickup_place,  presence: true, length: { maximum: 40 }
  validates :adults,        presence: true
  belongs_to :user

  after_save :setup_trip_price

  has_one    :budget,           :dependent => :destroy
  accepts_nested_attributes_for :budget

  has_one    :rythme,           :dependent => :destroy
  accepts_nested_attributes_for :rythme

  has_one    :style,            :dependent => :destroy
  accepts_nested_attributes_for :style

  has_one    :gestion,          :dependent=>  :destroy
  has_one    :livret,           :dependent=>  :destroy

  has_many   :plannings,                      :dependent => :destroy
  has_many   :days,      through: :plannings

  def setup_trip_price
    #to change price depending of number of people, no change until 4 people
    people_weight = (self.adults + self.kids/2) - 4
    people_weight = 1 if people_weight < 1
    new_price = 9 + (people_weight + 5)
    self.days.each do |day|
      new_price = new_price + day.price
    end
    self.update_column(:price, new_price)
  end

  def can_be_deleted?
    if ['new', 'pending', 'approved'].include? self.gestion.status
        return true
    else
      return false
    end
  end

  def can_be_edited?
    if self.gestion.status == 'new'
      return true
    else
      return false
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  #after_create :send_greeting_email

  has_one :account, :dependent => :destroy
  accepts_nested_attributes_for :account

  has_many :trips, :dependent => :destroy

  validates :email, presence: true
  validates :email, confirmation: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_fbomniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
   end
  end

  def self.from_igomniauth(auth)
    #instagram omniauth - Feature not implemented atm
  end

  def send_greeting_email
    # Sends email to user when user is created.
      MainMailer.greeting_email(self).deliver
  end

end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/days_helper.rb
module DaysHelper
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="alert alert-danger">
      <span>#{sentence}</span>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/setup_helper.rb
module SetupHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Une expérience unique pour visiter Tokyo : votre programme sur mesure fait par des experts locaux.">
    <meta name="author" content="">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <title>Visitez Tokyo sur mesure | Une expérience unique et personnelle pour découvrir Tokyo.</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if Rails.env.production? %>
      <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-105143670-1', 'auto');
      </script>
    <% end %>

  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top no-print" role="navigation">
      <div class="container surligne">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
            Menu <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand page-scroll" href="<%= root_path %>">
            <i class="fa fa-play-circle"></i> <span class="light">Tokyhop!</span>
          </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav">
            <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
            <li class="hidden"><a href="#page-top"></a></li>
            <li><%= link_to 'Que faire à Tokyo ?', themes_path, class: "page-scroll" %></li>
            <li><%= link_to 'Une question ?', root_path(anchor: 'contact-row'), class: "page-scroll" %></li>
            <% if current_user %>
              <li><%= link_to 'Mes voyages', trips_path, class: "page-scroll" %></li>
              <li><%= link_to 'Mon profil', user_path(current_user), class: "page-scroll" %></li>
              <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "page-scroll" %></li>
              <% if current_user && current_user.admin %>
                <li><%= link_to 'Admin', setup_index_path, class: "page-scroll" %></li>
              <% end %>
            <% else %>
              <li><%= link_to 'Se connecter',    new_user_session_path, class: "page-scroll" %></li>
              <li><%= link_to 'Créer un compte', new_user_registration_path, class: "page-scroll" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <section id="flash-section">
      <%if flash[:notice] %>
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
          <div class="alert alert-success alert-dismissable fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= flash[:notice] %>
          </div>
        </div>
      </div>
      <% end %>
      <%if flash[:alert] %>
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
            <div class="alert alert-warning alert-dismissable fade in">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              <%= flash[:alert] %>
            </div>
          </div>
        </div>
      <% end %>
    </section>

    <%= yield %>

    <footer class="no-print">
      <div class="container text-center">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <ul class="list-unstyled list-inline">
              <li><%= link_to 'Nous contacter', root_path(anchor: 'contact-row') %></li>
              <li><%= link_to 'Que faire à Tokyo ?', themes_path %></li>
              <li><%= link_to 'Informations', root_path %></li>
              <% if current_user %>
                <li><%= link_to 'Mes voyages', trips_path %></li>
                <li><%= link_to 'Mon profil', user_path(current_user) %></li>
                <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'Se connecter',    new_user_session_path(anchor: 'login-row')%></li>
                <li><%= link_to 'Créer un compte', new_user_registration_path%></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_3steps.html.erb
<section class="content-section text-center">
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <div class="circle-container">
        <div class="circle background-3step-01">
          <div class="step-blabla tagline">
            <h2 class="txt-on-img">Composez</h2>
            <div class="box"><div class="icon"><div class="image"><i class="fa"><strong>1</strong></i></div></div></div>
            <h4>Votre voyage sur mesure</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="circle-container">
        <div class="circle background-3step-02">
          <div class="step-blabla tagline">
            <h2 class="txt-on-img">Choisissez</h2>
            <div class="box"><div class="icon"><div class="image"><i class="fa"><strong>2</strong></i></div></div></div>
            <h4>Le thème de vos journées</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="circle-container">
        <div class="circle background-3step-03">
          <div class="step-blabla tagline">
            <h2 class="txt-on-img">Recevez</h2>
            <div class="box"><div class="icon"><div class="image"><i class="fa"><strong>3</strong></i></div></div></div>
            <h4>Votre programme de visite</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_commercial.html.erb
<!-- old commercial banner to revamp -->
<!-- Image Section
<section class="content-section text-center">
  <div class="row back-pink">
      <%= link_to '- Consultez toutes nos idées de visites -', themes_path, class: "btn btn-hop btn-block" %>
  </div>
    <div class="download-section" data-ajax="true">
        <div class="image-overlay"></div>
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
              <span class="txt-on-img theme-title">TOKYO</span>
          </div>
        </div>
    </div>
    <div class="row back-pink">
        <%= link_to '- Consultez toutes nos idées de visites -', themes_path, class: "btn btn-hop btn-block" %>
    </div>
</section> -->

app/views/shared/_contact.html.erb
<section  id="contact-row" class="content-section text-center">
  <div class="row tb-padding">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
      <div class="box"><div class="icon"><div class="image"><i class="fa fa-envelope"></i></div></div></div>
      <hr>
      <h2 class="tb-padding">Nous contacter</h2>
      <p>Une question, une demande ou un problème ? Nous sommes à votre écoute ! Envoyez-nous un message et nous vous répondrons
      dans les meilleurs délais.</p>
      <%= mail_to 'contact@tokyhop.fun', 'contact@tokyhop.fun', class: 'btn btn-lg btn-success' %>
      <hr>
    </div>
  </div>
</section>

app/views/shared/_infos.html.erb
<section  id="info-row" class="content-section text-center">
  <div class="row tb-padding">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
      <div class="box"><div class="icon"><div class="image"><i class="fa fa-star"></i></div></div></div>
      <h2>Découvrir Tokyo</h2>
    </div>
  </div>
  <div class="row text-left">
    <div class="col-xs-12 col-md-4">
      <p>
        <strong>Découvrir Tokyo</strong> est une expérience unique, mais parfois, difficile à organiser.
        Tokyhop s'occupe pour vous de l'organisation de votre voyage afin que vous puissiez profiter de Tokyo sans aucun
        stress. Transports, directions, où manger et que faire de vos journées, votre
        <%= link_to 'programme de visite', preview_path %> personnel vous libère de tous ces tracas logistiques.
      </p>
    </div>
    <div class="col-xs-12 col-md-4">
      <p>
        <strong>Nos experts locaux</strong> composent avec vous <%= link_to 'votre voyage', trips_path %>  selon vos souhaits
        et préparent votre <%= link_to 'programme de visite', preview_path %> personnel.  Pratique et détaillé, il vous guide
        pas-à-pas en toute tranquillité pendant votre séjour en tenant compte de vos goûts et de votre budget pour une expérience
        unique.
      </p>
    </div>
    <div class="col-xs-12 col-md-4">
      <p>
        <strong>Un Tokyo secret</strong> et charmant se laisse découvrir aux initiés. Nous accordons une grande importance
        à <%= link_to 'vous faire découvrir', themes_path %> la véritable âme de Tokyo en sortant des sentiers battus.
        Selon vos goûts, nous sélectionnons les visites, restaurants et activités qui vous correspondent pour composer
        votre parfaite expérience.
      </p>
    </div>
  </div>
  <div class="row text-left tb-padding">
    <div class="col-xs-12 col-md-4">
      <%= link_to 'Voir nos thèmes de visites', themes_path, class: 'btn btn-block btn-hop' %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= link_to 'Préparer mon voyage', trips_path, class: 'btn btn-block btn-hop' %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= link_to 'Nous contacter', root_path(anchor: 'contact-row'), class: 'btn btn-block btn-hop' %>
    </div>
  </div>
</section>

<%= render('shared/3steps') %>

<section class="intro">
  <div class="commercial-background background-image-01">
      <!-- background image div -->
  </div>
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="empty-space"></div>
      </div>
      <div class="row tb-padding tagline text-left">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
          <h1>Découvrez Tokyo</h1>
          <hr>
          <h3>A partir de 20€ / Jour</h3>
          <p>Recevez un programme de visite fait sur mesure par des experts locaux et découvrez un Tokyo
          authentique et secret.</p>
            <%= link_to "Préparer mon voyage", themes_path, class: "btn btn-block btn-hop" %>
        </div>
      </div>
    </div>
  </div>
</section>


<section  id="info-row" class="content-section text-center">
  <div class="row tb-padding">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
      <div class="box"><div class="icon"><div class="image"><i class="fa fa-heart"></i></div></div></div>
      <h2 class="tb-padding">Une expérience unique</h2>
      <p class="text-left"><%= link_to 'Que faire à Tokyo ?', themes_path %> Nous vous proposons une réponse personnelle et adaptée à vos souhaits. Avec Tokyhop,
        vous maîtrisez tous les aspects de votre voyage. Du budget aux restaurants, du rythme de vos journées à leur
        ambiance, de vos passions à vos envies, nous écoutons tous vos souhaits pour vous proposer <strong>votre</strong>
        expérience.<br>
        <strong>Simplement et rapidement,</strong> vous <%= link_to 'personnalisez votre séjour', trips_path %> en ligne depuis le site Tokyhop et choisissez <%= link_to 'les thèmes', themes_path %> de vos
        journées. Attentives à tous vos souhaits, nos équipes composent alors le programme de votre séjour à Tokyo.<br>
        <strong>Un programme fait avec passion,</strong> uniquement pour vous, et qui ne se contente pas des sites incontournables. Vous découvrirez
        aussi un Tokyo local et véritable, hors des sentiers battus. Vous profiterez des conseils de nos experts locaux pour
        découvrir des endroits cachés généralement innaccéssibles aux voyageurs.<br>
        Directions à prendre, que visiter, où vous restaurer, quelles boutiques sont intéressantes... Entièrement personnalisé
        pour vous par nos équipes, votre <%= link_to 'programme de visite', preview_path %> prend en compte la météo et les événements
        locaux pour vous proposer une journée inoubliable et unique à Tokyo.</p>
    </div>
  </div>
  <div class="row tb-padding">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
        <%= link_to "Préparer mon voyage", themes_path, class: "btn btn-block btn-hop" %>
      </div>
  </div>
</section>

<section  id="info-row" class="content-section text-center">
  <div class="row bottom-space tb-padding">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
      <div class="box"><div class="icon"><div class="image"><i class="fa fa-cogs"></i></div></div></div>
      <h2 class="tb-padding">Un séjour serein</h2>
      <p class="text-left"><strong>Un séjour à Tokyo </strong>n'est pas toujours facile. Pays lointain aux coutumes si différentes, langue mystérieuse et réseau de
        transports abracadabrantesque, nous vous délestons de tous ses tracas logistiques en organisant vos journées de A à Z pour que vous
        puissiez profiter pleinement de la magie de Tokyo sans stress.<br>
        <strong>Nos guides partagent</strong> avec vous leurs découvertes et leur passion à travers votre programme. Mangez dans de délicieux
        restaurants locaux, déambulez dans des ruelles vibrantes encore du charme de l'ancienne Edo et découvrez des boutiques
        originales, antres de collectionneurs passionnés.<br>
        Votre <%= link_to 'programme de visite', preview_path %> vous guide pas-à-pas, depuis votre hôtel, tout au long de votre journée.
        Facile à utiliser, votre programme vous indique quels transports emprunter et vous guide avec des indications claires et faciles
        ainsi qu'avec des cartes personnelles montrant votre parcours et les centres d'intérêts.<br>
        Votre <%= link_to 'programme de visite', preview_path %> est disponible en ligne à tout moment et peut-être facilement imprimé
        à volonté.</p>
    </div>
  </div>
  <div class="row tb-padding">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
        <%= link_to "Préparer mon voyage", themes_path, class: "btn btn-block btn-hop" %>
      </div>
  </div>
</section>

<section  id="info-row" class="content-section text-center">
  <div class="row tb-padding">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
      <div class="box"><div class="icon"><div class="image"><i class="fa fa-hand-peace-o"></i></div></div></div>
      <h2 class="tb-padding">Une équipe passionnée</h2>
      <p class="text-left"><strong>Nos experts locaux</strong> comptent des Japonais passionnés de leurs villes, mais aussi des
        Français vivant à Tokyo depuis de nombreuses années. Cosmopolite et jeune, notre équipe a pour vocation
        de faire découvrir un Tokyo authentique et original.<br>
        Basés à Tokyo, nous sommes à votre écoute avant et pendant votre séjour pour que votre expérience y soit la plus douce
        possible. Nous mettons à votre service notre amour du Japon et de Tokyo afin que vous puissiez profiter de toutes
        les découvertes de nos équipes.<br>
        Vous pouvez nous <%= link_to 'contacter par email', '#contact-row' %> si vous avez la moindre question sur votre prochain séjour.</p>
    </div>
  </div>
  <div class="row tb-padding">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
        <%= link_to "Préparer mon voyage", themes_path, class: "btn btn-block btn-hop" %>
      </div>
  </div>
</section>

<section class="intro">
  <div class="commercial-background background-image-02">
      <!-- background image div -->
  </div>
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="empty-space"></div>
      </div>
      <div class="row tb-padding tagline text-left">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
          <h1>Une expérience unique</h1>
          <hr>
          <h3>Maitrisez votre voyage</h3>
          <p>Personalisez votre séjour et partez en toute confiance : une équipe d'experts locaux veille
          pour s'assurer que votre voyage se passe sans aucun souci.</p>
          <%= link_to "Préparer mon voyage", themes_path, class: "btn btn-block btn-hop" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/themes/details/deprecated/_hakone.html.erb
<section class="container content-section text-center tb-padding">
    <div class="row">
      <div class="col-xs-12">
        <div class="box tb-padding"><div class="icon"><div class="image"><i class="fa fa-map-marker"></i></div></div></div>
        <p>
          A moins de 2 heures de Tokyo, la station thermale de Hakone permet de passer une journée intéressante dans un cadre magnifique.
          Au coeur de montagnes boisées, cette région volcanique offre aussi des onsens formidables pour se détendre après vos escapades dans
          Tokyo. Par temps clair, il est possible d'appercevoir le mont Fuji depuis le lac Ashi.<br>
          Les fans du manga Evangélion seront ravis de visiter le lieu où Tokyo3 fut bati. :)
        </p>
      </div>
    </div>
</section>
<br>
<section class="container content-section text-center tb-padding">
    <div class="row">
      <div class="col-md-6">
        <h1>Le lac Ashi</h1>
        <p>Au pied des montagnes, le lac d'Ashi offre par temps clair une belle vue sur le mont Fuji. La traversé du lac se fait de manière
          plaisante sur un bateau pirate et permettra de belles photos. En bordure de lac, au coeur d'une foret de cèdre se trouve le charmant
          temple de Hakone.
        </p>
      </div>
      <div class="col-md-6">
        <%= image_tag 'asakusa005.jpg', class: "img-responsive tb-padding" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h1>Owakudani</h1>
        <p>Après une montée en téléphérique, vous pourrez profiter de la vue et également des vapeurs de souffres s'échappant des
          sources volcaniques proches. Ici, il vous est possible de manger des oeufs durs, cuits directement dans les eaux volcaniques
        bouillonantes. La coquille de l'oeuf est noircie par le souffre. Il est dit que consommer un de ces oeufs prolonge sa vie de
        7 années.</p>
      </div>
      <div class="col-md-6">
        <%= image_tag 'asakusa004.jpg', class: "img-responsive tb-padding" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h1>Onsen</h1>
        <p>La région de Hakone est une destination populaire pour ses Onsen. Ses sources thermales japonaises sont une activité familliale
          populaire pendant les week-ends et les vacances. Particulièrement relaxante, un Onsen en fin de journée, avant votre retour à Tokyo
        sera une expèrience inoubliable.</p>
      </div>
      <div class="col-md-6">
        <%= image_tag 'asakusa004.jpg', class: "img-responsive tb-padding" %>
      </div>
    </div>
</section>